import { authOptions } from "@/lib/auth-options";
import { getServerSession } from "next-auth";
import { Open_Sans, Playfair_Display } from "next/font/google";
import NextAuthProvider from "../components/SessionsProvider";
import "./globals.css";
import "../styles/scroll-bar.css";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";

const openSans = Open_Sans({ subsets: ["latin"] });
const playfairDisplay = Playfair_Display({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      />
      <body className={cn(openSans.className, "dark")}>
        <NextAuthProvider session={session}>
          {children}
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
